const objectConstants = {
  OBJECT_LIST_REQUEST: "OBJECT_LIST_REQUEST",
  OBJECT_LIST_SUCCESS: "OBJECT_LIST_SUCCESS",
  OBJECT_LIST_FAIL: "OBJECT_LIST_FAIL",
  
  USER_DEPENDENCIES_REQUEST : "USER_DEPENDENCIES_REQUEST",
  USER_DEPENDENCIES_SUCCESS : "USER_DEPENDENCIES_SUCCESS",
  USER_DEPENDENCIES_FAIL : "USER_DEPENDENCIES_FAIL"
}

export default objectConstants;