const objectConstants = {
  OBJECT_LIST_REQUEST: "OBJECT_LIST_REQUEST",
  OBJECT_LIST_SUCCESS: "OBJECT_LIST_SUCCESS",
  OBJECT_LIST_FAIL: "OBJECT_LIST_FAIL",
  
  USER_DEPENDENCIES_REQUEST : "USER_DEPENDENCIES_REQUEST",
  USER_DEPENDENCIES_SUCCESS : "USER_DEPENDENCIES_SUCCESS",
  USER_DEPENDENCIES_FAIL: "USER_DEPENDENCIES_FAIL",
  
  SELECT_OBJECT_REQUEST : "SELECT_OBJECT_REQUEST",
  SELECT_OBJECT_SUCCESS : "SELECT_OBJECT_SUCCESS",
  SELECT_OBJECT_FAIL: "SELECT_OBJECT_FAIL",
  
  UNSELECT_OBJECT_REQUEST : "UNSELECT_OBJECT_REQUEST",
  UNSELECT_OBJECT_SUCCESS : "UNSELECT_OBJECT_SUCCESS",
  UNSELECT_OBJECT_FAIL: "UNSELECT_OBJECT_FAIL",
  
  OPERATION_RESULT_REQUEST : "OPERATION_RESULT_REQUEST",
  OPERATION_RESULT_SUCCESS : "OPERATION_RESULT_SUCCESS",
  OPERATION_RESULT_FAIL: "OPERATION_RESULT_FAIL",
  
  SET_GRAPH_DATA_REQUEST : "SET_GRAPH_DATA_REQUEST",
  SET_GRAPH_DATA_SUCCESS : "SET_GRAPH_DATA_SUCCESS",
  SET_GRAPH_DATA_FAIL   :  "SET_GRAPH_DATA_FAIL"
}

export default objectConstants;