const tableConstants = {
  TABLE_DEPENDENCIES_REQUEST: "TABLE_DEPENDENCIES_REQUEST",
  TABLE_DEPENDENCIES_SUCCESS: "TABLE_DEPENDENCIES_SUCCESS",
  TABLE_DEPENDENCIES_FAIL: "TABLE_DEPENDENCIES_FAIL",

  TABLE_LIST_REQUEST: "TABLE_LIST_REQUEST",
  TABLE_LIST_SUCCESS: "TABLE_LIST_SUCCESS",
  TABLE_LIST_FAIL: "TABLE_LIST_FAIL",
}

export default tableConstants;