const userConstants = {
  NEW_CONNECTION_REQUEST : 'NEW_CONNECTION_REQUEST',
  NEW_CONNECTION_SUCCESS : 'NEW_CONNECTION_SUCCESS',
  NEW_CONNECTION_FAIL: 'NEW_CONNECTION_FAIL',
  
  ALL_CONNECTION_REQUEST: 'ALL_CONNECTION_REQUEST',
  ALL_CONNECTION_SUCCESS: 'ALL_CONNECTION_SUCCESS',
  ALL_CONNECTION_FAIL: 'ALL_CONNECTION_FAIL',

  SET_CONNECTION_REQUEST: 'SET_CONNECTION_REQUEST',
  SET_CONNECTION_SUCCESS: 'SET_CONNECTION_SUCCESS',
  SET_CONNECTION_FAIL: 'SET_CONNECTION_FAIL',
  
  DELETE_CONNECTION_REQUEST: 'DELETE_CONNECTION_REQUEST',
  DELETE_CONNECTION_SUCCESS: 'DELETE_CONNECTION_SUCCESS',
  DELETE_CONNECTION_FAIL: 'DELETE_CONNECTION_FAIL',
  
  EDIT_CONNECTION_REQUEST: 'EDIT_CONNECTION_REQUEST',
  EDIT_CONNECTION_SUCCESS: 'EDIT_CONNECTION_SUCCESS',
  EDIT_CONNECTION_FAIL:    'EDIT_CONNECTION_FAIL'
}

export default userConstants;