const userConstants = {
  NEW_CONNECTION_REQUEST : 'NEW_CONNECTION_REQUEST',
  NEW_CONNECTION_SUCCESS : 'NEW_CONNECTION_SUCCESS',
  NEW_CONNECTION_FAIL    : 'NEW_CONNECTION_FAIL'
}

export default userConstants;